-- MySQL Script generated by MySQL Workbench
-- Tue May 14 23:20:03 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`UserInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UserInfo` (
  `userID` VARCHAR(45) NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_login` TIMESTAMP NOT NULL,
  `userType` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userID`));


-- -----------------------------------------------------
-- Table `mydb`.`StoreInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`StoreInfo` (
  `StoreID` INT NOT NULL,
  `StoreName` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NULL,
  `City` VARCHAR(45) NULL,
  `State` VARCHAR(45) NULL,
  `Country` VARCHAR(45) NULL,
  `zipCode` VARCHAR(45) NULL,
  `Phone` VARCHAR(45) NULL,
  PRIMARY KEY (`StoreID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`storeLocation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`storeLocation` (
  `locationID` INT NOT NULL,
  `storeID` INT NOT NULL,
  `Address` VARCHAR(45) NULL,
  `City` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `zipCode` VARCHAR(45) NULL,
  `Country` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  PRIMARY KEY (`locationID`),
  INDEX `fk_storeLocation_StoreInfo_idx` (`storeID` ASC) VISIBLE,
  CONSTRAINT `fk_storeLocation_StoreInfo`
    FOREIGN KEY (`storeID`)
    REFERENCES `mydb`.`StoreInfo` (`StoreID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`userTransaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`userTransaction` (
  `userID` VARCHAR(45) NOT NULL,
  `transactionType` VARCHAR(45) NULL,
  `tansactionDate` VARCHAR(45) NULL,
  `transactionAmount` VARCHAR(45) NULL,
  `points` VARCHAR(45) NULL,
  `locationID` INT NOT NULL,
  INDEX `fk_userTransaction_UserInfo1_idx` (`userID` ASC) VISIBLE,
  INDEX `fk_userTransaction_storeLocation1_idx` (`locationID` ASC) VISIBLE,
  CONSTRAINT `fk_userTransaction_UserInfo1`
    FOREIGN KEY (`userID`)
    REFERENCES `mydb`.`UserInfo` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_userTransaction_storeLocation1`
    FOREIGN KEY (`locationID`)
    REFERENCES `mydb`.`storeLocation` (`locationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
